#!/usr/bin/env python3
"""Fail the docs build when a page references an asset that isn't on disk.

Broken images have shipped to the live site more than once. The usual cause is a
mangled path in the Markdown source (a bulk rewrite once turned every
``UI_sim.png`` into ``UI*sim.png``), which Jekyll happily builds because it never
resolves ``<img src>``.

Run against a built site::

    python docs/tests/check_assets.py _site

Only local references are checked; ``http(s)://``, ``data:``, ``mailto:`` and
fragment-only URLs are skipped, as is ``api/`` (generated by MkDocs).
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from urllib.parse import unquote, urlparse

# The built site is served under the repo's baseurl on GitHub Pages, so
# absolute URLs in the HTML carry this prefix while _site itself does not.
BASEURL = "/TI-Toolbox"

MEDIA_ATTR = re.compile(
    r"<(?:img|source|video|audio|embed)\b[^>]*?\b(?:src|srcset|poster)\s*=\s*[\"']([^\"']+)",
    re.IGNORECASE,
)
SKIP_DIRS = {"api", "assets/vendor"}


def _is_external(url: str) -> bool:
    return (
        not url
        or url.startswith(("#", "//", "data:", "mailto:", "javascript:"))
        or bool(urlparse(url).scheme)
    )


def check(site: Path) -> list[str]:
    problems: list[str] = []
    for page in sorted(site.rglob("*.html")):
        rel = page.relative_to(site).as_posix()
        if any(rel == d or rel.startswith(d + "/") for d in SKIP_DIRS):
            continue
        html = page.read_text(encoding="utf-8", errors="ignore")
        for raw in MEDIA_ATTR.findall(html):
            if _is_external(raw):
                # checked before splitting: a data: URI's base64 payload
                # contains commas and must not be treated as a srcset list
                continue
            # srcset can hold a comma-separated candidate list
            for candidate in raw.split(","):
                url = candidate.strip().split(" ")[0]
                if _is_external(url):
                    continue
                url = unquote(url.split("#")[0].split("?")[0])
                if not url:
                    continue
                if url.startswith(BASEURL + "/") or url == BASEURL:
                    url = url[len(BASEURL):] or "/"
                target = (
                    site / url.lstrip("/") if url.startswith("/") else page.parent / url
                )
                if not target.exists():
                    problems.append(f"{rel}: missing asset {url}")
    return problems


def main() -> int:
    site = Path(sys.argv[1] if len(sys.argv) > 1 else "_site")
    if not site.is_dir():
        print(f"error: built site not found at {site}", file=sys.stderr)
        return 2
    problems = check(site)
    if problems:
        print(f"{len(problems)} broken asset reference(s):", file=sys.stderr)
        for p in problems:
            print(f"  {p}", file=sys.stderr)
        return 1
    print("All local asset references resolve.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
