services:
  matlab:
    image: idossha/matlab:20th
    platform: linux/amd64
    container_name: matlab_container
    volumes:
      - matlab_runtime:/usr/local/MATLAB/MATLAB_Runtime
    networks:
      - ti_network
    restart: unless-stopped
  
  fsl:
    image: idossha/ti-csc_fsl:v1.3.0
    platform: linux/amd64
    container_name: fsl_container
    volumes:
      - ti_csc_fsl_data:/usr/local/fsl/
    networks:
      - ti_network
    restart: unless-stopped
 
  freesurfer:
    image: idossha/ti-csc_freesurfer:v1.3.0
    platform: linux/amd64
    container_name: freesurfer_container
    volumes:
      - ti_csc_freesurfer_data:/usr/local/freesurfer/
    networks:
      - ti_network
    restart: unless-stopped

  simnibs:
    image: idossha/simnibs:2.0.4
    platform: linux/amd64
    container_name: simnibs_container
    volumes:
      - ti_csc_fsl_data:/usr/local/fsl/
      - ti_csc_freesurfer_data:/usr/local/freesurfer/
      - matlab_runtime:/usr/local/MATLAB/MATLAB_Runtime
      - ${LOCAL_PROJECT_DIR}:/mnt/${PROJECT_DIR_NAME}
      # X11 socket mount for Linux/macOS
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      # Additional mount for macOS XQuartz compatibility
      - ${HOME}/.Xauthority:/root/.Xauthority:rw
    environment:
      # User environment
      USER: root
      # Display configuration
      DISPLAY: ${DISPLAY}
      # OpenGL configuration for software rendering (better compatibility)
      LIBGL_ALWAYS_SOFTWARE: "1"
      QT_X11_NO_MITSHM: "1"
      # FSL environment
      FSLDIR: /usr/local/fsl
      FSLOUTPUTTYPE: NIFTI_GZ
      FSLMULTIFILEQUIT: "TRUE"
      POSSUMDIR: /usr/local/fsl
      # FreeSurfer environment
      FREESURFER_HOME: /usr/local/freesurfer
      SUBJECTS_DIR: /usr/local/freesurfer/subjects
      FS_LICENSE: /usr/local/freesurfer/license.txt
      # Project paths
      LOCAL_PROJECT_DIR: ${LOCAL_PROJECT_DIR}
      PROJECT_DIR_NAME: ${PROJECT_DIR_NAME}
      # Performance settings
      KMP_AFFINITY: "disabled"
      # MATLAB Runtime paths
      LD_LIBRARY_PATH: /usr/local/MATLAB/MATLAB_Runtime/v124/runtime/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v124/bin/glnxa64:/usr/local/MATLAB/MATLAB_Runtime/v124/sys/os/glnxa64
      XAPPLRESDIR: /usr/local/MATLAB/MATLAB_Runtime/v124/X11/app-defaults
    networks:
      - ti_network
    depends_on:
      - fsl
      - freesurfer
      - matlab
    tty: true
    stdin_open: true
    working_dir: /ti-csc
    command: ["/bin/bash"]
    restart: unless-stopped

networks:
  ti_network:
    driver: bridge

volumes:
  ti_csc_fsl_data:
    external: true
    name: ti_csc_fsl_data
  ti_csc_freesurfer_data:
    external: true
    name: ti_csc_freesurfer_data
  matlab_runtime:
    external: true
    name: matlab_runtime

