# Codecov Configuration for TI-Toolbox
# Documentation: https://docs.codecov.com/docs/codecov-yaml

# Coverage report settings
codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes

# Coverage targets and thresholds
coverage:
  precision: 2
  round: down
  range: "60...100"

  status:
    # Overall project coverage
    project:
      default:
        target: 70%
        threshold: 2%
        base: auto
        if_ci_failed: error

    # Coverage for individual patches/PRs
    patch:
      default:
        target: 65%
        threshold: 5%
        base: auto
        if_ci_failed: error

# Component-specific coverage flags
# These match the flags passed in CircleCI: -F unittests,core,simulator,analyzer,optimizer
flags:
  unittests:
    paths:
      - tests/
    carryforward: false

  core:
    paths:
      - tit/core/
    carryforward: false
    target: 80%

  simulator:
    paths:
      - tit/sim/
    carryforward: false
    target: 70%

  analyzer:
    paths:
      - tit/analyzer/
    carryforward: false
    target: 75%

  optimizer:
    paths:
      - tit/opt/
    carryforward: false
    target: 65%

  stats:
    paths:
      - tit/stats/
    carryforward: false
    target: 60%

  plotting:
    paths:
      - tit/plotting/
    carryforward: false
    target: 60%

  preprocessing:
    paths:
      - tit/pre/
    carryforward: false
    target: 60%

# Files to ignore in coverage reports
ignore:
  - "**/__pycache__"
  - "**/*.pyc"
  - "**/test_*.py"
  - "tests/**"
  - "setup.py"
  - "version.py"
  - "**/gui/**"  # GUI code is harder to test in headless environments
  - "**/__init__.py"  # Init files are often just imports

# Comment configuration for pull requests
comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - main
    - master

# GitHub status checks configuration
github_checks:
  annotations: true
