#!/bin/bash

# Source FreeSurfer environment setup script
if [ -n "$FREESURFER_HOME" ] && [ -f "$FREESURFER_HOME/SetUpFreeSurfer.sh" ]; then
    source "$FREESURFER_HOME/SetUpFreeSurfer.sh" >/dev/null 2>&1
fi

# Setup CLI tools if present
if [ -d /ti-toolbox/cli ]; then
    chmod +x /ti-toolbox/cli/*.sh
    export PATH="$PATH:/ti-toolbox/cli"
fi

# Setup XDG runtime directory
export XDG_RUNTIME_DIR=/tmp/runtime-root
mkdir -p "$XDG_RUNTIME_DIR"
chmod 700 "$XDG_RUNTIME_DIR"

# ============================================================================
# Container-side initialization functions (moved from loader.sh)
# ============================================================================

# Function to create hidden files cross-platform
create_hidden_file() {
    local file_path="$1"
    local content="$2"
    
    if [ -n "$content" ]; then
        echo "$content" > "$file_path"
    else
        touch "$file_path"
    fi
    
    case "$(uname -s)" in
        MINGW*|MSYS*|CYGWIN*)
            attrib +h "$file_path" >/dev/null 2>&1
            ;;
        *)
            # Unix-like (macOS/Linux) - files are hidden if they start with a dot
            ;;
    esac
}

# Function to get version from version.py
get_version() {
    local version_file="/ti-toolbox/../../version.py"
    if [ -f "$version_file" ]; then
        grep "__version__" "$version_file" | sed 's/.*"\(.*\)".*/\1/'
    else
        echo "unknown"
    fi
}

# Function to initialize BIDS dataset_description.json in the project root
initialize_dataset_description() {
    local dataset_file="$LOCAL_PROJECT_DIR/dataset_description.json"
    local assets_template="/ti-toolbox/../../resources/dataset_descriptions/root.dataset_description.json"
    local fallback_template="/ti-toolbox/../../new_project/dataset_description.json"

    if [ -f "$dataset_file" ]; then
        return 0
    fi

    if [ ! -d "$LOCAL_PROJECT_DIR" ]; then
        return 1
    fi

    local project_name="${PROJECT_DIR_NAME:-$(basename "$LOCAL_PROJECT_DIR")}"

    if [ -f "$assets_template" ]; then
        cp "$assets_template" "$dataset_file" || return 1
    elif [ -f "$fallback_template" ]; then
        cp "$fallback_template" "$dataset_file" || return 1
    else
        return 1
    fi
    
    sed -i.tmp "s/\"Name\": \"\"/\"Name\": \"$project_name\"/" "$dataset_file" && rm -f "${dataset_file}.tmp"

    if [ -f "$dataset_file" ]; then
        return 0
    else
        return 1
    fi
}

# Function to initialize BIDS README file in the project root
initialize_readme() {
    local readme_file="$LOCAL_PROJECT_DIR/README"
    
    if [ -f "$readme_file" ]; then
        return 0
    fi

    if [ ! -d "$LOCAL_PROJECT_DIR" ]; then
        return 1
    fi

    local project_name="${PROJECT_DIR_NAME:-$(basename "$LOCAL_PROJECT_DIR")}"

    cat > "$readme_file" << EOF
# $project_name

This is a BIDS-compliant neuroimaging dataset generated by TI-Toolbox for temporal interference (TI) stimulation modeling and analysis.

## Overview

This project contains structural MRI data and derivatives for simulating and analyzing temporal interference electric field patterns in the brain.

## Dataset Structure

- \`sourcedata/\` - Raw DICOM source files
- \`sub-*/\` - Subject-level BIDS-formatted neuroimaging data (NIfTI files)
- \`derivatives/\` - Processed data and analysis results
  - \`freesurfer/\` - FreeSurfer anatomical segmentation and surface reconstructions
  - \`SimNIBS/\` - SimNIBS head models and electric field simulations
  - \`ti-toolbox/\` - TI-Toolbox simulation results and analyses

## Software

Data processing and simulations were performed using:
- **TI-Toolbox** - Temporal interference modeling pipeline
- **FreeSurfer** - Cortical reconstruction and volumetric segmentation
- **SimNIBS** - Finite element modeling for electric field simulations

## More Information

For more information about TI-Toolbox, visit:
- GitHub: https://github.com/idossha/TI-Toolbox
- Documentation: https://idossha.github.io/TI-toolbox/

## BIDS Compliance

This dataset follows the Brain Imaging Data Structure (BIDS) specification for organizing and describing neuroimaging data. For more information about BIDS, visit: https://bids.neuroimaging.io/
EOF

    if [ -f "$readme_file" ]; then
        return 0
    else
        return 1
    fi
}

# Function to initialize ti-toolbox derivative dataset_description.json
initialize_ti_toolbox_derivative() {
    local derivatives_dir="$LOCAL_PROJECT_DIR/derivatives"
    local ti_toolbox_dir="$derivatives_dir/ti-toolbox"
    local dataset_file="$ti_toolbox_dir/dataset_description.json"
    local assets_template="/ti-toolbox/../../resources/dataset_descriptions/ti-toolbox.dataset_description.json"

    if [ -f "$dataset_file" ]; then
        return 0
    fi

    mkdir -p "$ti_toolbox_dir" || return 1

    if [ ! -f "$assets_template" ]; then
        return 1
    fi

    if cp "$assets_template" "$dataset_file"; then
        local project_name="${PROJECT_DIR_NAME:-$(basename "$LOCAL_PROJECT_DIR")}"
        local current_date=$(date +"%Y-%m-%d")
        
        sed -i.tmp "s/\"URI\": \"\"/\"URI\": \"bids:$project_name@$current_date\"/" "$dataset_file" && rm -f "${dataset_file}.tmp"
        sed -i.tmp "s/\"DatasetLinks\": {}/\"DatasetLinks\": {\n    \"$project_name\": \"..\/..\/\"\n  }/" "$dataset_file" && rm -f "${dataset_file}.tmp"
        
        return 0
    else
        return 1
    fi
}

# Function to initialize FreeSurfer derivative dataset_description.json
initialize_freesurfer_derivative() {
    local derivatives_dir="$LOCAL_PROJECT_DIR/derivatives"
    local freesurfer_dir="$derivatives_dir/freesurfer"
    local dataset_file="$freesurfer_dir/dataset_description.json"
    local assets_template="/ti-toolbox/../../resources/dataset_descriptions/freesurfer.dataset_description.json"

    if [ -f "$dataset_file" ]; then
        return 0
    fi

    mkdir -p "$freesurfer_dir" || return 1

    if [ ! -f "$assets_template" ]; then
        return 1
    fi

    if cp "$assets_template" "$dataset_file"; then
        local project_name="${PROJECT_DIR_NAME:-$(basename "$LOCAL_PROJECT_DIR")}"
        local current_date=$(date +"%Y-%m-%d")
        
        sed -i.tmp "s/\"URI\": \"\"/\"URI\": \"bids:$project_name@$current_date\"/" "$dataset_file" && rm -f "${dataset_file}.tmp"
        sed -i.tmp "s/\"DatasetLinks\": {}/\"DatasetLinks\": {\n    \"$project_name\": \"..\/..\/\"\n  }/" "$dataset_file" && rm -f "${dataset_file}.tmp"
        
        return 0
    else
        return 1
    fi
}

# Function to initialize SimNIBS derivative dataset_description.json
initialize_simnibs_derivative() {
    local derivatives_dir="$LOCAL_PROJECT_DIR/derivatives"
    local simnibs_dir="$derivatives_dir/SimNIBS"
    local dataset_file="$simnibs_dir/dataset_description.json"
    local assets_template="/ti-toolbox/../../resources/dataset_descriptions/simnibs.dataset_description.json"

    if [ -f "$dataset_file" ]; then
        return 0
    fi

    mkdir -p "$simnibs_dir" || return 1

    if [ ! -f "$assets_template" ]; then
        return 1
    fi

    if cp "$assets_template" "$dataset_file"; then
        local project_name="${PROJECT_DIR_NAME:-$(basename "$LOCAL_PROJECT_DIR")}"
        local current_date=$(date +"%Y-%m-%d")
        
        sed -i.tmp "s/\"URI\": \"\"/\"URI\": \"bids:$project_name@$current_date\"/" "$dataset_file" && rm -f "${dataset_file}.tmp"
        sed -i.tmp "s/\"DatasetLinks\": {}/\"DatasetLinks\": {\n    \"$project_name\": \"..\/..\/\"\n  }/" "$dataset_file" && rm -f "${dataset_file}.tmp"
        
        return 0
    else
        return 1
    fi
}

# Function to setup example data for new projects
setup_example_data_if_new() {
    local example_data_manager="/ti-toolbox/new_project/example_data_manager.py"
    
    if [ ! -f "$example_data_manager" ]; then
        return 1
    fi
    
    if command -v python3 >/dev/null 2>&1; then
        if python3 "$example_data_manager" "/ti-toolbox/../.." "$LOCAL_PROJECT_DIR" 2>/dev/null; then
            return 0
        fi
    fi
    return 1
}

# Function to check if project is new and initialize config files
initialize_project_configs() {
    local project_ti_csc_dir="$LOCAL_PROJECT_DIR/code/ti-toolbox"
    local project_config_dir="$project_ti_csc_dir/config"
    local new_project_configs_dir="/ti-toolbox/new_project/configs"
    local is_new_project=false

    if [ ! -d "$project_ti_csc_dir" ]; then
        mkdir -p "$project_config_dir"
        is_new_project=true
    elif [ ! -d "$project_config_dir" ]; then
        mkdir -p "$project_config_dir"
        is_new_project=true
    fi

    if [ "$is_new_project" = true ]; then
        if [ ! -d "$new_project_configs_dir" ]; then
            return 1
        fi
        
        for config_file in "$new_project_configs_dir"/*.json; do
            if [ -f "$config_file" ]; then
                filename=$(basename "$config_file")
                
                if [ "$filename" = "entrypoint.json" ]; then
                    continue
                fi
                
                target_file="$project_config_dir/$filename"
                
                if [ ! -f "$target_file" ]; then
                    cp "$config_file" "$target_file"
                fi
            fi
        done
        
        chmod -R 755 "$project_config_dir"

        local info_dir="$LOCAL_PROJECT_DIR/derivatives/ti-toolbox/.ti-toolbox-info"
        mkdir -p "$info_dir"
        
        local status_content='{
  "project_created": "",
  "last_updated": "",
  "config_created": false,
  "example_data_copied": false,
  "user_preferences": {
    "show_welcome": true
  },
  "project_metadata": {
    "name": "",
    "path": "",
    "version": ""
  }
}'
        create_hidden_file "$info_dir/project_status.json" "$status_content"
        chmod -R 755 "$info_dir"
        
        initialize_dataset_description >/dev/null 2>&1
        initialize_readme >/dev/null 2>&1
        setup_example_data_if_new >/dev/null 2>&1
    fi

    echo "$is_new_project"
}

# Function to write project status
write_project_status() {
    local info_dir="$LOCAL_PROJECT_DIR/derivatives/ti-toolbox/.ti-toolbox-info"
    local status_file="$info_dir/project_status.json"
    mkdir -p "$info_dir"

    local is_new_project=$(initialize_project_configs)

    if [ "$is_new_project" = false ] && [ -f "$status_file" ]; then
        if command -v jq >/dev/null 2>&1; then
            if ! jq empty "$status_file" >/dev/null 2>&1; then
                cp "$status_file" "${status_file}.bak_$(date +%s)"
                cat > "$status_file" << EOF
{
  "project_created": "$(date -u +"%Y-%m-%dT%H:%M:%S.%6N")",
  "last_updated": "$(date -u +"%Y-%m-%dT%H:%M:%S.%6N")",
  "config_created": true,
  "user_preferences": { "show_welcome": true },
  "project_metadata": {
    "name": "$(basename "$LOCAL_PROJECT_DIR")",
    "path": "$(printf "%s" "$LOCAL_PROJECT_DIR" | tr -d '\r')",
    "version": "$(get_version)"
  }
}
EOF
            fi
        fi
        sed -i.tmp "s/\"last_updated\": \".*\"/\"last_updated\": \"$(date -u +"%Y-%m-%dT%H:%M:%S.%6N")\"/" "$status_file"
        rm -f "${status_file}.tmp"
    fi
}

# Function to write system info to a hidden folder in the project directory
write_system_info() {
    local info_dir="$LOCAL_PROJECT_DIR/derivatives/ti-toolbox/.ti-toolbox-info"
    local info_file="$info_dir/system_info.txt"
    mkdir -p "$info_dir"

    {
        echo "# TI-Toolbox System Info"
        echo "Date: $(date)"
        echo "User: $(whoami)"
        echo "Host: $(hostname)"
        echo "OS: $(uname -a)"
        echo ""
        echo "## Disk Space (project dir)"
        df -h "$LOCAL_PROJECT_DIR" 2>/dev/null || echo "N/A"
        echo ""
        echo "## DISPLAY"
        echo "$DISPLAY"
        echo ""
        echo "## Environment Variables (TI-Toolbox relevant)"
        env | grep -Ei '^(FREESURFER|SIMNIBS|PROJECT_DIR|SUBJECTS_DIR|FS_LICENSE|DISPLAY|USER|PATH)=' || echo "N/A"
        echo ""
    } > "$info_file"

    create_hidden_file "$info_file"
}

# ============================================================================
# Initialize project environment if LOCAL_PROJECT_DIR is set
# ============================================================================

if [ -n "$LOCAL_PROJECT_DIR" ]; then
    # Create derivatives directories for BIDS compliance
    mkdir -p "$LOCAL_PROJECT_DIR/derivatives/ti-toolbox"
    mkdir -p "$LOCAL_PROJECT_DIR/derivatives/freesurfer"
    mkdir -p "$LOCAL_PROJECT_DIR/derivatives/SimNIBS"
    
    # Initialize BIDS files and project status
    initialize_dataset_description >/dev/null 2>&1
    initialize_ti_toolbox_derivative >/dev/null 2>&1
    initialize_freesurfer_derivative >/dev/null 2>&1
    initialize_simnibs_derivative >/dev/null 2>&1
    
    # Write project info
    write_project_status >/dev/null 2>&1
    write_system_info >/dev/null 2>&1
fi

# Start interactive shell if no command provided
if [ $# -eq 0 ]; then
    exec /bin/bash
else
    exec "$@"
fi
