from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable

from . import example_data_manager


MARKER_FILES = (
    "code/ti-toolbox/config/.initialized",
    "code/ti-toolbox/config/project_status.json",
    "dataset_description.json",
    "README",
)


def _dir_has_files(path: Path, *, patterns: Iterable[str] | None = None) -> bool:
    if not path.exists() or not path.is_dir():
        return False
    if patterns:
        for pattern in patterns:
            if any(p.is_file() for p in path.rglob(pattern)):
                return True
        return False
    return any(p.is_file() for p in path.rglob("*"))


def has_project_data_or_markers(project_dir: Path) -> bool:
    for marker in MARKER_FILES:
        if (project_dir / marker).exists():
            return True

    if any(project_dir.glob("sub-*")):
        return True

    if _dir_has_files(
        project_dir / "sourcedata", patterns=("*.dcm", "*.nii", "*.nii.gz")
    ):
        return True

    if _dir_has_files(project_dir / "derivatives"):
        return True

    if any(project_dir.glob("*.nii*")):
        return True

    return False


def is_new_project(project_dir: Path) -> bool:
    return (
        project_dir.exists()
        and project_dir.is_dir()
        and not has_project_data_or_markers(project_dir)
    )


def initialize_readme(project_dir: Path) -> None:
    readme_file = project_dir / "README"
    if readme_file.exists():
        return
    project_name = project_dir.name
    readme_content = f"""# {project_name}

This is a BIDS-compliant neuroimaging dataset generated by TI-Toolbox for temporal interference (TI) stimulation modeling and analysis.

## Overview

This project contains structural MRI data and derivatives for simulating and analyzing temporal interference electric field patterns in the brain.

## Dataset Structure

- `sourcedata/` - Raw DICOM source files
- `sub-*/` - Subject-level BIDS-formatted neuroimaging data (NIfTI files)
- `derivatives/` - Processed data and analysis results
  - `freesurfer/` - FreeSurfer anatomical segmentation and surface reconstructions
  - `SimNIBS/` - SimNIBS head models and electric field simulations
  - `ti-toolbox/` - TI-Toolbox simulation results and analyses

## Software

Data processing and simulations were performed using:
- **TI-Toolbox** - Temporal interference modeling pipeline
- **FreeSurfer** - Cortical reconstruction and volumetric segmentation
- **SimNIBS** - Finite element modeling for electric field simulations

## More Information

For more information about TI-Toolbox, visit:
- GitHub: https://github.com/idossha/TI-Toolbox
- Documentation: https://idossha.github.io/TI-toolbox/

## BIDS Compliance

This dataset follows the Brain Imaging Data Structure (BIDS) specification for organizing and describing neuroimaging data. For more information about BIDS, visit: https://bids.neuroimaging.io/
"""
    readme_file.write_text(readme_content)


def initialize_dataset_description(project_dir: Path) -> None:
    dataset_file = project_dir / "dataset_description.json"
    if dataset_file.exists():
        return
    payload = {
        "Name": project_dir.name,
        "BIDSVersion": "1.6.0",
        "DatasetType": "raw",
        "License": "",
        "Authors": [],
        "Acknowledgements": "",
        "HowToAcknowledge": "",
        "Funding": [],
        "ReferencesAndLinks": ["https://github.com/idossha/TI-Toolbox"],
        "DatasetDOI": "",
    }
    dataset_file.write_text(json.dumps(payload, indent=2))


def initialize_derivative_dataset_description(
    project_dir: Path, derivative_name: str
) -> None:
    derivative_dir = project_dir / "derivatives" / derivative_name
    dataset_file = derivative_dir / "dataset_description.json"
    if dataset_file.exists():
        return
    derivative_dir.mkdir(parents=True, exist_ok=True)
    current_date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    payload = {
        "Name": f"{derivative_name} derivatives",
        "BIDSVersion": "1.6.0",
        "DatasetType": "derivative",
        "GeneratedBy": [{"Name": derivative_name}],
        "SourceDatasets": [
            {"URI": f"bids:{project_dir.name}@{current_date}", "Version": "1.0.0"}
        ],
        "DatasetLinks": {project_dir.name: "../../"},
    }
    dataset_file.write_text(json.dumps(payload, indent=2))


def initialize_project_status(project_dir: Path) -> None:
    config_dir = project_dir / "code" / "ti-toolbox" / "config"
    status_file = config_dir / "project_status.json"
    config_dir.mkdir(parents=True, exist_ok=True)
    current_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S")
    payload = {
        "project_created": current_time,
        "last_updated": current_time,
        "config_created": True,
        "example_data_copied": False,
        "user_preferences": {"show_welcome": True},
        "project_metadata": {
            "name": project_dir.name,
            "path": str(project_dir),
            "version": "unknown",
        },
    }
    status_file.write_text(json.dumps(payload, indent=2))


def initialize_project_structure(project_dir: Path) -> None:
    print("")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print(f"  New project detected: {project_dir.name}")
    print("  Initializing BIDS-compliant structure...")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("")

    print("Creating directory structure...")
    (project_dir / "code" / "ti-toolbox" / "config").mkdir(parents=True, exist_ok=True)
    (project_dir / "derivatives" / "freesurfer").mkdir(parents=True, exist_ok=True)
    (project_dir / "derivatives" / "SimNIBS").mkdir(parents=True, exist_ok=True)
    (project_dir / "sourcedata").mkdir(parents=True, exist_ok=True)
    print("  ✓ Directories created")

    print("Creating BIDS metadata files...")
    initialize_readme(project_dir)
    print("  ✓ README created")

    initialize_dataset_description(project_dir)
    print("  ✓ Root dataset_description.json created")

    initialize_derivative_dataset_description(project_dir, "ti-toolbox")
    print("  ✓ ti-toolbox dataset_description.json created")

    initialize_derivative_dataset_description(project_dir, "freesurfer")
    print("  ✓ freesurfer dataset_description.json created")

    initialize_derivative_dataset_description(project_dir, "SimNIBS")
    print("  ✓ SimNIBS dataset_description.json created")

    print("Creating project configuration...")
    initialize_project_status(project_dir)
    print("  ✓ Project status file created")

    (project_dir / "code" / "ti-toolbox" / "config" / ".initialized").touch()
    print("  ✓ Initialization marker created")

    print("")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("  ✓ Project initialization complete!")
    print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━")
    print("")


def setup_example_data(toolbox_root: Path, project_dir: Path) -> bool:
    try:
        success, _subjects = example_data_manager.setup_example_data(
            str(toolbox_root), str(project_dir)
        )
        return bool(success)
    except Exception:
        return False
