"""
References reportlet for TI-Toolbox reports.

This module provides the default citations and references used across
TI-Toolbox reports.
"""

from typing import Any, Dict, List, Optional

from ..core.base import ReferencesReportlet


# Default TI-Toolbox references
DEFAULT_REFERENCES: List[Dict[str, str]] = [
    # ==========================================================================
    # Core TI & SimNIBS references
    # ==========================================================================
    {
        "key": "ti",
        "citation": (
            "Grossman N, et al. Noninvasive deep brain stimulation via "
            "temporally interfering electric fields. Cell. 2017 Jun;169(6):"
            "1029-1041.e16."
        ),
        "doi": "10.1016/j.cell.2017.05.024",
    },
    {
        "key": "simnibs",
        "citation": (
            "Thielscher A, Antunes A, Saturnino GB. Field modeling for "
            "transcranial magnetic stimulation: a useful tool to understand "
            "the physiological effects of TMS?. In: 2015 37th Annual "
            "International Conference of the IEEE Engineering in Medicine "
            "and Biology Society (EMBC). Milan: IEEE; Aug. 2015. p. 222-5."
        ),
        "doi": "10.1109/EMBC.2015.7318340",
    },
    {
        "key": "simnibs4",
        "citation": (
            "Saturnino GB, Puonti O, Nielsen JD, Antonenko D, Madsen KH, "
            "Thielscher A. SimNIBS 2.1: a comprehensive pipeline for "
            "individualized electric field modelling for transcranial brain "
            "stimulation. In: Makarov S, Horner M, Noetscher G, editors. "
            "Brain and Human Body Modeling. Cham: Springer International "
            "Publishing; 2019. p. 3-25."
        ),
        "doi": "10.1007/978-3-030-21293-3_1",
    },
    {
        "key": "charm",
        "citation": (
            "Puonti O, Van Leemput K, Saturnino GB, Siebner HR, Madsen KH, "
            "Thielscher A. Accurate and robust whole-head segmentation from "
            "magnetic resonance images for individualized head modeling. "
            "NeuroImage. 2020 Oct;219:117044."
        ),
        "doi": "10.1016/j.neuroimage.2020.117044",
    },
    # ==========================================================================
    # Simulation-specific references
    # ==========================================================================
    {
        "key": "multipolar_ti",
        "citation": (
            "Botzanowski B, et al. Focal control of non-invasive deep brain "
            "stimulation using multipolar temporal interference. Bioelectron "
            "Med. 2025 Mar;11(1):7."
        ),
        "doi": "10.1186/s42234-025-00169-6",
    },
    {
        "key": "electrode_params",
        "citation": (
            "Saturnino GB, Antunes A, Thielscher A. On the importance of "
            "electrode parameters for shaping electric field patterns "
            "generated by tDCS. NeuroImage. 2015 Oct;120:25-35."
        ),
        "doi": "10.1016/j.neuroimage.2015.06.067",
    },
    {
        "key": "quasi_static",
        "citation": (
            "Gaugain G, et al. Quasi-static approximation error of electric "
            "field analysis for transcranial current stimulation. J Neural "
            "Eng. 2023 Feb;20(1):016027."
        ),
        "doi": "10.1088/1741-2552/acb14d",
    },
    {
        "key": "tdcs_determinants",
        "citation": (
            "Opitz A, Paulus W, Will S, Antunes A, Thielscher A. Determinants "
            "of the electric field during transcranial direct current "
            "stimulation. NeuroImage. 2015 Apr;109:140-50."
        ),
        "doi": "10.1016/j.neuroimage.2015.01.033",
    },
    # ==========================================================================
    # Atlas references
    # ==========================================================================
    {
        "key": "icbm",
        "citation": (
            "Mazziotta J, et al. A probabilistic atlas and reference system "
            "for the human brain: International Consortium for Brain Mapping "
            "(ICBM). Philos Trans R Soc Lond B Biol Sci. 2001 Aug;356(1412):"
            "1293-322."
        ),
        "doi": "10.1098/rstb.2001.0915",
    },
    {
        "key": "glasser",
        "citation": (
            "Glasser MF, et al. A multi-modal parcellation of human cerebral "
            "cortex. Nature. 2016 Aug;536(7615):171-8."
        ),
        "doi": "10.1038/nature18933",
    },
    {
        "key": "destrieux",
        "citation": (
            "Destrieux C, Fischl B, Dale A, Halgren E. Automatic parcellation "
            "of human cortical gyri and sulci using standard anatomical "
            "nomenclature. NeuroImage. 2010 Oct;53(1):1-15."
        ),
        "doi": "10.1016/j.neuroimage.2010.06.010",
    },
    {
        "key": "mcrib",
        "citation": (
            "Alexander B, et al. Desikan-Killiany-Tourville atlas compatible "
            "version of M-CRIB neonatal parcellated whole brain atlas: the "
            "M-CRIB 2.0. Front Neurosci. 2019 Feb;13:34."
        ),
        "doi": "10.3389/fnins.2019.00034",
    },
    # ==========================================================================
    # EEG electrode positioning
    # ==========================================================================
    {
        "key": "eeg_positions",
        "citation": (
            "Jurcak V, Tsuzuki D, Dan I. 10/20, 10/10, and 10/5 systems "
            "revisited: their validity as relative head-surface-based "
            "positioning systems. NeuroImage. 2007 Feb;34(4):1600-11."
        ),
        "doi": "10.1016/j.neuroimage.2006.09.024",
    },
    {
        "key": "egi_sensor_nets",
        "citation": "Geodesic Sensor Nets. Electrical Geodesics, Inc.",
        "url": "https://www.egi.com/clinical-division/geodesic-sensor-nets",
    },
    # ==========================================================================
    # Preprocessing & data format references
    # ==========================================================================
    {
        "key": "freesurfer",
        "citation": (
            "Fischl B. FreeSurfer. NeuroImage. 2012 Aug;62(2):774-81."
        ),
        "doi": "10.1016/j.neuroimage.2012.01.021",
    },
    {
        "key": "bids",
        "citation": (
            "Gorgolewski KJ, et al. The brain imaging data structure, a "
            "format for organizing and describing outputs of neuroimaging "
            "experiments. Sci Data. 2016 Jun;3(1):160044."
        ),
        "doi": "10.1038/sdata.2016.44",
    },
    {
        "key": "bids_apps",
        "citation": (
            "Gorgolewski KJ, et al. BIDS apps: improving ease of use, "
            "accessibility, and reproducibility of neuroimaging data analysis "
            "methods. PLoS Comput Biol. 2017 Mar;13(3):e1005209."
        ),
        "doi": "10.1371/journal.pcbi.1005209",
    },
    {
        "key": "qsiprep",
        "citation": (
            "Cieslak M, et al. QSIPrep: an integrative platform for "
            "preprocessing and reconstructing diffusion MRI data. "
            "Nat Methods. 2021 Jul;18(7):775-778."
        ),
        "doi": "10.1038/s41592-021-01185-5",
    },
    {
        "key": "dcm2niix",
        "citation": (
            "Li X, Morgan PS, Ashburner J, Smith J, Rorden C. The first step "
            "for neuroimaging data analysis: DICOM to NIfTI conversion. "
            "J Neurosci Methods. 2016 May;264:47-56."
        ),
        "doi": "10.1016/j.jneumeth.2016.03.001",
    },
    # ==========================================================================
    # Flex-search / optimization references
    # ==========================================================================
    {
        "key": "leadfield_free",
        "citation": (
            "Weise K, Madsen KH, Worbs T, Knosche TR, Korshoj A, Thielscher A. "
            "A leadfield-free optimization framework for transcranially "
            "applied electric currents. bioRxiv. 2024 Dec 20."
        ),
        "doi": "10.1101/2024.12.18.629095",
    },
    # ==========================================================================
    # DTI / Anisotropic conductivity references
    # ==========================================================================
    {
        "key": "charmed",
        "citation": (
            "Assaf Y, Basser PJ. Composite hindered and restricted model of "
            "diffusion (CHARMED) MR imaging of the human brain. NeuroImage. "
            "2005 Aug;27(1):48-58."
        ),
        "doi": "10.1016/j.neuroimage.2005.03.042",
    },
    {
        "key": "dti_conductivity",
        "citation": (
            "Rullmann M, Anwander A, Dannhauer M, Warfield SK, Duffy FH, "
            "Wolters CH. EEG source analysis of epileptiform activity using "
            "a 1 mm anisotropic hexahedra finite element head model. "
            "NeuroImage. 2009 Feb;44(2):399-410."
        ),
        "doi": "10.1016/j.neuroimage.2008.09.009",
    },
    # ==========================================================================
    # Meshing & visualization (for future use)
    # ==========================================================================
    {
        "key": "gmsh",
        "citation": (
            "Geuzaine C, Remacle J-F. Gmsh: a 3-D finite element mesh "
            "generator with built-in pre- and post-processing facilities. "
            "Int J Numer Methods Eng. 2009;79(11):1309-31."
        ),
        "doi": "10.1002/nme.2579",
    },
    {
        "key": "blender",
        "citation": "Blender - Free and Open 3D Creation Software.",
        "url": "https://github.com/blender/blender",
    },
]


class TIToolboxReferencesReportlet(ReferencesReportlet):
    """
    Specialized references reportlet with TI-Toolbox default citations.

    Automatically includes relevant citations based on the pipeline
    components used.
    """

    def __init__(
        self,
        title: Optional[str] = None,
        include_defaults: bool = True,
        pipeline_components: Optional[List[str]] = None,
    ):
        """
        Initialize the TI-Toolbox references reportlet.

        Args:
            title: Section title
            include_defaults: Whether to include default TI-Toolbox refs
            pipeline_components: List of components used (to filter refs)
        """
        super().__init__(title=title or "References")

        self.pipeline_components = pipeline_components or []

        if include_defaults:
            self._add_default_references()

    def _add_default_references(self) -> None:
        """Add default references based on pipeline components."""
        # Report-type specific complete reference sets
        # These define ALL references for each report type (no core refs added)
        report_type_refs = {
            "simulation": [
                "ti", "simnibs", "icbm", "charm", "multipolar_ti",
                "electrode_params", "quasi_static", "eeg_positions",
                "egi_sensor_nets",
            ],
            "simulator": [
                "ti", "simnibs", "icbm", "charm", "multipolar_ti",
                "electrode_params", "quasi_static", "eeg_positions",
                "egi_sensor_nets",
            ],
            "preprocessing": [
                "simnibs", "freesurfer", "icbm", "charm", "mcrib",
                "destrieux", "glasser", "bids", "bids_apps",
                "tdcs_determinants", "eeg_positions", "egi_sensor_nets",
                "simnibs4",
            ],
            "flex-search": [
                "simnibs", "charm", "leadfield_free", "mcrib",
                "destrieux", "glasser",
            ],
        }

        # Tool/component-specific additional references
        component_ref_map = {
            # Tool-specific mappings
            "freesurfer": ["freesurfer"],
            "qsiprep": ["qsiprep"],
            "dcm2niix": ["dcm2niix"],
            "dti": ["charmed", "dti_conductivity", "qsiprep"],
            "anisotropic": ["charmed", "dti_conductivity"],
            # Atlas mappings
            "glasser": ["glasser"],
            "destrieux": ["destrieux"],
            "mcrib": ["mcrib"],
            "icbm": ["icbm"],
            # Other mappings
            "bids": ["bids", "bids_apps"],
            "eeg": ["eeg_positions", "egi_sensor_nets"],
            "electrodes": ["electrode_params", "eeg_positions", "egi_sensor_nets"],
            "mesh": ["gmsh"],
            "visualization": ["blender"],
        }

        refs_to_add: set = set()

        # Check if any component is a report type with a complete ref set
        for component in self.pipeline_components:
            component_lower = component.lower()
            if component_lower in report_type_refs:
                refs_to_add.update(report_type_refs[component_lower])

        # If no report type matched, use default core refs
        if not refs_to_add:
            refs_to_add = {"ti", "simnibs", "simnibs4", "charm"}

        # Add any additional component-specific references
        for component in self.pipeline_components:
            component_lower = component.lower()
            if component_lower in component_ref_map:
                refs_to_add.update(component_ref_map[component_lower])

        # Add references
        for ref_data in DEFAULT_REFERENCES:
            if ref_data["key"] in refs_to_add:
                self.add_reference(
                    key=ref_data["key"],
                    citation=ref_data["citation"],
                    doi=ref_data.get("doi"),
                    url=ref_data.get("url"),
                )

    def add_default_reference(self, key: str) -> bool:
        """
        Add a default reference by key.

        Args:
            key: The reference key (e.g., 'freesurfer', 'qsiprep')

        Returns:
            True if reference was found and added, False otherwise
        """
        for ref_data in DEFAULT_REFERENCES:
            if ref_data["key"] == key:
                # Check if already added
                if not any(r["key"] == key for r in self.references):
                    self.add_reference(
                        key=ref_data["key"],
                        citation=ref_data["citation"],
                        doi=ref_data.get("doi"),
                        url=ref_data.get("url"),
                    )
                return True
        return False


def get_default_references() -> List[Dict[str, str]]:
    """
    Get the list of default TI-Toolbox references.

    Returns:
        List of reference dictionaries
    """
    return DEFAULT_REFERENCES.copy()


def get_reference_by_key(key: str) -> Optional[Dict[str, str]]:
    """
    Get a specific reference by its key.

    Args:
        key: The reference key

    Returns:
        Reference dictionary or None if not found
    """
    for ref in DEFAULT_REFERENCES:
        if ref["key"] == key:
            return ref.copy()
    return None
