/**
 * The contextBridge object the preload exposes as `window.tit`.
 *
 * Present only inside the Electron shell. In browser mode (the same bundle opened in a normal
 * browser) `window.tit` is undefined and the renderer hides Electron-only controls.
 *
 * Invariant: the server token never reaches the server-served renderer. It is typed into the
 * local launcher page (or generated by `stack.start`, never seen by the renderer at all), sent to
 * the main process once and exchanged for an HttpOnly cookie by the server.
 *
 * `TitBridge` is exactly 12 entries — every one of them a round trip through the main process
 * (never a capability the renderer holds directly, per R5's IPC-only-for-host-access rule):
 *
 *  1. `platform`            — host OS, for platform-specific copy/shortcuts.
 *  2. `appVersion`          — desktop shell version (not the toolbox image's).
 *  3. `openExternal`        — http(s)/mailto in the OS default browser.
 *  4. `connect`             — launcher <-> session handshake (health + token check, or return-to-launcher).
 *  5. `getSettings`         — read `TitSettings` (last server URL, last project dir).
 *  6. `setSettings`         — merge-patch `TitSettings`. Launcher-only (ra_14 finding 4): a
 *                             server-served page could otherwise poison `lastProjectDir` for the
 *                             next launch.
 *  7. `selectDirectory`     — host directory picker (the launcher's *project* picker only).
 *                             Launcher-only (ra_14 finding 4) and unlike `selectFile`, its result
 *                             is a raw host path (`stack.start` needs one), never mapped into a
 *                             project — a server-served page has no legitimate use for it.
 *  8. `selectFile`          — host file picker (`PathInput` onBrowse, ra_13 finding 8). Callable
 *                             from any page (this is a real, in-use per-field Browse button); the
 *                             picked host path is mapped through the known project mount before it
 *                             is returned, so a page only ever receives a *container* path, never
 *                             the raw host one — `undefined` (with the reason logged in main) when
 *                             the pick falls outside every known mount.
 *  9. `openPath`            — open a server-given path with the OS default app (host<->container
 *                             mapping: `stack.getCurrent()`'s mount, else `GET /api/project`'s
 *                             `host_path` when this app did not itself start the stack). Rejects a
 *                             path with a literal `.`/`..` segment outright (ra_14 finding 3) and
 *                             refuses to resolve one that does not map into a known mount, rather
 *                             than falling back to the unmapped string.
 * 10. `showItemInFolder`    — reveal a server-given path in Finder/Explorer; same mapping and
 *                             rejection rules as `openPath`.
 * 11. `notify`              — native desktop notification.
 * 12. `stack`               — the Docker lifecycle sub-bridge (`start`/`stop`/`status`/`onEvent`),
 *                             counted as one entry even though it is itself a small object.
 *                             `start` is launcher-only (ra_14 finding 4); `status` (read-only) and
 *                             `stop` (ends only the caller's own container) are not.
 *
 * ADR row 14 budgets 12 top-level entries and this is still exactly 12: the in-app "Stop Docker
 * stack" control (QA engineer finding 6) added no bridge entry at all — `stack.stop()` and
 * `stack.status()` already existed, `stop` widened its sender check in main, and `status` grew
 * three descriptive fields. The preload file is untouched.
 *
 * Extend this list's numbering when adding or removing a top-level `TitBridge` member.
 */
export interface TitSettings {
  /** Last server URL the user connected to. The token is never stored. */
  lastServerUrl?: string;
  /** Last project directory picked, so the launcher/project picker can default to it. */
  lastProjectDir?: string;
}

export interface TitConnectArgs {
  url: string;
  token: string;
}

export type TitConnectResult = { ok: true } | { ok: false; error: string };

export interface TitSelectFileOptions {
  filters?: { name: string; extensions: string[] }[];
}

export type TitStackStartResult = { ok: true; attached: boolean } | { ok: false; error: string };
export type TitStackStopResult = { ok: true } | { ok: false; error: string };

export interface TitStackStatus {
  running: boolean;
  hostProjectDir?: string;
  port?: number;
  /** `docker ps` name of the container this app started or attached to. */
  containerName?: string;
  /** Image reference the container runs, tag included. */
  image?: string;
  /** Docker's own healthcheck verdict; `"none"` when the image declares no healthcheck. */
  health?: "starting" | "healthy" | "unhealthy" | "none";
}

/** Progress/lifecycle events from `stack.start`/`stack.stop`, forwarded live to the renderer. */
export type TitStackEvent =
  | { type: "progress"; stage: string; message: string }
  | { type: "started"; port: number; attached: boolean }
  | { type: "stopped" }
  | { type: "error"; message: string };

export interface TitStackBridge {
  /**
   * Discover-or-start the Docker stack for `hostProjectDir` and load its session (attach-or-start).
   * Launcher-only (ra_14 finding 4) — a server-served page must not be able to mount an arbitrary
   * host directory (plus docker.sock) into a fresh root container.
   */
  start(hostProjectDir: string): Promise<TitStackStartResult>;
  /**
   * Stop and remove the currently-attached stack's container, if any. Callable from the launcher
   * *and* from the connected app (Settings -> Docker): the page that calls it is served by the
   * container it stops, so it can only end its own session — no other project, no host path, no
   * new mount. Stopping from a server-served page returns the window to the launcher.
   */
  stop(): Promise<TitStackStopResult>;
  status(): Promise<TitStackStatus>;
  /** Subscribe to live progress; returns an unsubscribe function. */
  onEvent(callback: (event: TitStackEvent) => void): () => void;
}

export interface TitBridge {
  /** `process.platform` of the host. */
  platform(): NodeJS.Platform;
  /** Version of the desktop shell (package.json), not of the toolbox image. */
  appVersion(): Promise<string>;
  /** Open an http(s)/mailto URL in the host's default browser (scheme-checked in main). */
  openExternal(url: string): Promise<void>;
  /**
   * With arguments: wait for `<url>/api/health` (only allowed from the launcher page) and load
   * the session URL in this window. Without arguments: return to the launcher page.
   */
  connect(args?: TitConnectArgs): Promise<TitConnectResult>;
  getSettings(): Promise<TitSettings>;
  /** Launcher-only (ra_14 finding 4) — see the numbered list above. */
  setSettings(partial: Partial<TitSettings>): Promise<TitSettings>;
  /**
   * Host directory picker for the launcher's *project* picker only. Launcher-only (ra_14
   * finding 4); its result is a raw host path (`stack.start` needs one), never mapped into a
   * project — unlike `selectFile`, below.
   */
  selectDirectory(): Promise<string | undefined>;
  /**
   * Host file picker (`PathInput` `onBrowse` for a file field, ra_13 finding 8). Callable from any
   * page — the picked host path is mapped through the known project mount (`stack.getCurrent()`'s
   * mount, or `GET /api/project`'s `host_path`) before it is returned, so callers only ever get a
   * *container* path. Resolves to `undefined` both when the user cancels the dialog and when the
   * picked path falls outside every known mount (the reason is logged in main, not surfaced here —
   * there is no secret in a "no mount" case, only a path the caller has no way to use anyway).
   */
  selectFile(options?: TitSelectFileOptions): Promise<string | undefined>;
  /**
   * Open a path (as given by the server — a container path when a project is mounted, mapped to
   * the host path internally) with the OS default application. Host<->container mapping prefers
   * the stack this app itself started (`stack.getCurrent()`'s mount); when there is none (e.g. a
   * manually-typed server URL), main falls back to `GET /api/project`'s own `host_path` (fetched
   * with the bearer token, never exposed to the renderer). A path containing a literal `.`/`..`
   * segment, or one that does not map into a known mount, is refused outright — `{ok:false,
   * reason}` — rather than opened unresolved (ra_14 finding 3); `reason` is safe to show the user
   * (it never echoes the original path or any secret). `{ok:true}` means `shell.openPath` reported
   * no error; a resolved-but-nonexistent path still comes back as `{ok:false, reason}` with the
   * OS's own error text.
   */
  openPath(path: string): Promise<{ ok: boolean; reason?: string }>;
  /** Reveal a path in Finder/Explorer/the file manager — same mapping and rejection rules as `openPath`. */
  showItemInFolder(path: string): Promise<{ ok: boolean; reason?: string }>;
  /** Fire a native desktop notification. No-ops silently where notifications are unsupported. */
  notify(title: string, body?: string): Promise<void>;
  stack: TitStackBridge;
}

declare global {
  interface Window {
    tit?: TitBridge;
  }
}
