#!/usr/bin/env simnibs_python
"""Render the deep-vs-superficial focality comparison figure and HTML report.

Reads ``results.json`` produced by :mod:`run_comparison` and writes
``comparison.png`` and ``report.html`` beside it. The 2x2 figure plots each
run's objective trajectory over valid (FEM-evaluated) candidates; the deep/ROC
cell is expected to be flat (constant objective -> no gradient), while the other
three vary. A "flatness" column (objective spread = max - min) quantifies it.

Usage
-----
    simnibs_python make_report.py [results.json]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

DEPTHS = ["superficial", "deep"]
GOALS = ["focality", "focality_integral"]
GOAL_LABEL = {"focality": "ROC (threshold-based)", "focality_integral": "Integral (threshold-free)"}


def _cell(results, depth, goal):
    for c in results["cells"]:
        if c.get("depth") == depth and c.get("goal") == goal:
            return c
    return None


def _spread(traj):
    return (max(traj) - min(traj)) if traj else 0.0


def make_figure(results, png_path: Path) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(11, 8), constrained_layout=True)
    fig.suptitle(
        "Flex-search objective trajectory: ROC vs integral focality "
        f"(subject {results.get('subject', '?')})",
        fontsize=14, fontweight="bold",
    )
    for i, depth in enumerate(DEPTHS):
        for j, goal in enumerate(GOALS):
            ax = axes[i][j]
            cell = _cell(results, depth, goal)
            traj = cell["trajectory"] if cell else []
            if traj:
                ax.plot(range(1, len(traj) + 1), traj, "-o", ms=3, lw=1.3)
                sp = _spread(traj)
                ax.set_title(
                    f"{depth} x {GOAL_LABEL[goal]}\nspread={sp:.3g}  best={cell.get('best_value')}",
                    fontsize=10,
                )
                # Flag a degenerate (flat) landscape.
                if sp < 1e-6:
                    ax.text(0.5, 0.5, "FLAT\n(no gradient)", transform=ax.transAxes,
                            ha="center", va="center", color="crimson",
                            fontsize=16, fontweight="bold", alpha=0.7)
            else:
                ax.set_title(f"{depth} x {GOAL_LABEL[goal]}\n(no data)", fontsize=10)
                ax.text(0.5, 0.5, "pending / no valid evals", transform=ax.transAxes,
                        ha="center", va="center", color="gray")
            ax.set_xlabel("valid evaluation #")
            ax.set_ylabel("objective (minimized)")
            ax.grid(True, alpha=0.3)
    fig.savefig(png_path, dpi=130)
    plt.close(fig)


def make_html(results, png_path: Path, html_path: Path) -> None:
    rows = []
    for depth in DEPTHS:
        for goal in GOALS:
            c = _cell(results, depth, goal) or {}
            traj = c.get("trajectory", [])
            rows.append(
                f"<tr><td>{depth}</td><td>{GOAL_LABEL[goal]}</td>"
                f"<td>{c.get('n_evaluations', 0)}</td>"
                f"<td>{_spread(traj):.4g}</td>"
                f"<td>{c.get('best_value')}</td>"
                f"<td>{c.get('elapsed_sec')}</td></tr>"
            )
    budget = results.get("budget", {})
    html = f"""<!doctype html><meta charset="utf-8">
<title>Integral focality vs ROC — {results.get('subject','?')}</title>
<style>
 body{{font-family:-apple-system,Segoe UI,Roboto,sans-serif;max-width:960px;margin:2rem auto;padding:0 1rem;line-height:1.5}}
 table{{border-collapse:collapse;width:100%;margin:1rem 0}}
 th,td{{border:1px solid #ccc;padding:.4rem .6rem;text-align:left;font-size:.92rem}}
 th{{background:#f4f4f4}} img{{max-width:100%;border:1px solid #ddd;border-radius:6px}}
 code{{background:#f4f4f4;padding:.1rem .3rem;border-radius:3px}}
</style>
<h1>Deep vs superficial focality: ROC vs integral</h1>
<p>Subject <code>{results.get('subject','?')}</code>. Budget:
   maxiter={budget.get('maxiter')}, popsize={budget.get('popsize')}, cpus={budget.get('cpus')}.</p>
<p>Each cell shows the flex-search objective over valid (FEM-evaluated) candidates.
   A near-zero <b>spread</b> means the objective is flat — differential evolution has
   no gradient to follow. The ROC objective is expected to flatten at the deep target
   (both thresholds jointly infeasible), while integral focality stays optimizable.</p>
<img src="{png_path.name}" alt="objective trajectory comparison">
<table>
 <tr><th>Target</th><th>Goal</th><th>valid evals</th><th>objective spread</th><th>best objective</th><th>elapsed (s)</th></tr>
 {''.join(rows)}
</table>
<p style="color:#666;font-size:.85rem">Generated by <code>examples/focality_integral_ernie/make_report.py</code>.
   Lower budgets converge less but reach the same qualitative conclusion.</p>
"""
    html_path.write_text(html)


def main() -> None:
    results_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("results.json")
    results = json.loads(results_path.read_text())
    out_dir = results_path.parent
    png = out_dir / "comparison.png"
    html = out_dir / "report.html"
    make_figure(results, png)
    make_html(results, png, html)
    print(f"Wrote {png}\nWrote {html}")


if __name__ == "__main__":
    main()
