#!/usr/bin/env simnibs_python
# -*- coding: utf-8 -*-

"""Create subject-space functional thalamus ROIs from MNI templates.

The generated masks are written under::

    derivatives/SimNIBS/sub-<sid>/m2m_<sid>/ROIs/thalamus_functional/

For each subject the tool creates anterior, central, and posterior masks for
left, right, and bilateral thalamus.  The left/right masks are warped from MNI
space; bilateral masks are created as exact unions in subject space.
"""

from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np

from tit.paths import get_path_manager

THALAMUS_TARGETS = ("anterior", "central", "posterior")
THALAMUS_SIDES = ("left", "right")
ROI_SUBDIR = "thalamus_functional"
MNI_TEMPLATE_DIRNAME = "thalamus_functional_mni"


@dataclass(frozen=True)
class ThalamusROIResult:
    """Summary of one generated thalamus ROI mask."""

    subject_id: str
    target: str
    side: str
    path: Path
    voxel_count: int
    created: bool


def _subject_id(subject_id: str) -> str:
    return str(subject_id).strip().removeprefix("sub-")


def _repo_resource_template_dir() -> Path:
    return Path(__file__).resolve().parents[2] / "resources" / "atlas" / MNI_TEMPLATE_DIRNAME


def find_thalamus_template_dir(
    project_dir: str | Path | None = None,
    template_dir: str | Path | None = None,
) -> Path:
    """Return the MNI template directory used for functional thalamus ROIs."""

    candidates: list[Path] = []
    if template_dir is not None:
        candidates.append(Path(template_dir))
    if project_dir is not None:
        candidates.append(
            Path(project_dir) / "derivatives" / "ti-toolbox" / "rois" / MNI_TEMPLATE_DIRNAME
        )
    candidates.append(_repo_resource_template_dir())

    for candidate in candidates:
        if candidate.is_dir():
            return candidate

    searched = "\n".join(f"  - {path}" for path in candidates)
    raise FileNotFoundError(
        "Could not find functional thalamus MNI templates. Expected files such as "
        f"thalamus_anterior_left_MNI.nii.gz in one of:\n{searched}"
    )


def _template_path(template_dir: Path, target: str, side: str) -> Path:
    return template_dir / f"thalamus_{target}_{side}_MNI.nii.gz"


def _template_json_path(template_dir: Path, target: str, side: str) -> Path:
    return template_dir / f"thalamus_{target}_{side}_MNI.json"


def _output_path(output_dir: Path, subject_id: str, target: str, side: str) -> Path:
    return output_dir / f"thalamus_{target}_{side}_sub-{subject_id}.nii.gz"


def _sidecar_path(nii_path: Path) -> Path:
    return nii_path.with_name(nii_path.name.removesuffix(".nii.gz") + ".json")


def _load_template_metadata(template_dir: Path, target: str, side: str) -> dict:
    path = _template_json_path(template_dir, target, side)
    if not path.exists():
        return {}
    with path.open() as f:
        return json.load(f)


def _load_binary_mask(path: Path) -> tuple[np.ndarray, object]:
    import nibabel as nib

    img = nib.load(str(path))
    data = np.asanyarray(img.dataobj)
    return data > 0, img


def _save_binary_mask(mask: np.ndarray, reference_img: object, output_path: Path) -> None:
    import nibabel as nib

    output_path.parent.mkdir(parents=True, exist_ok=True)
    header = reference_img.header.copy()
    header.set_data_dtype(np.uint8)
    img = nib.Nifti1Image(mask.astype(np.uint8), reference_img.affine, header)
    nib.save(img, str(output_path))


def _warp_volume(source: Path, m2m_dir: Path, output: Path, reference: Path) -> None:
    from simnibs.utils import transformations

    transformations.warp_volume(
        str(source),
        str(m2m_dir),
        str(output),
        transformation_direction="mni2subject",
        transformation_type="nonl",
        reference=str(reference),
        order=0,
        method="nearest",
        binary=True,
    )


def _write_sidecar(
    output_path: Path,
    *,
    subject_id: str,
    target: str,
    side: str,
    voxel_count: int,
    source_metadata: dict | None = None,
    source_files: Iterable[Path] = (),
    m2m_dir: Path,
) -> None:
    source_metadata = source_metadata or {}
    labels = source_metadata.get("labels", [])
    payload = {
        "name": f"thalamus_{target}_{side}",
        "space": f"sub-{subject_id} subject space",
        "source_space": source_metadata.get("space", "MNI"),
        "source_atlas": source_metadata.get("source_atlas"),
        "source_mni_rois": [str(path) for path in source_files],
        "labels": labels,
        "voxels_subject": int(voxel_count),
        "m2m_dir": str(m2m_dir),
        "note": (
            "Generated by TI-Toolbox from shared MNI functional thalamus ROI "
            "templates using SimNIBS mni2subject warping."
        ),
    }
    _sidecar_path(output_path).write_text(json.dumps(payload, indent=2) + "\n")


def _validate_templates(template_dir: Path) -> None:
    missing: list[Path] = []
    for target in THALAMUS_TARGETS:
        for side in THALAMUS_SIDES:
            path = _template_path(template_dir, target, side)
            if not path.exists():
                missing.append(path)
    if missing:
        details = "\n".join(f"  - {path}" for path in missing)
        raise FileNotFoundError(f"Missing functional thalamus ROI templates:\n{details}")


def create_thalamus_functional_rois(
    project_dir: str | Path,
    subject_id: str,
    *,
    template_dir: str | Path | None = None,
    output_dir: str | Path | None = None,
    overwrite: bool = False,
) -> list[ThalamusROIResult]:
    """Create subject-space anterior/central/posterior thalamus ROI masks.

    Parameters
    ----------
    project_dir
        BIDS project root.
    subject_id
        Subject identifier, with or without ``sub-`` prefix.
    template_dir
        Optional directory containing ``thalamus_*_MNI.nii.gz`` templates.
    output_dir
        Optional output directory.  Defaults to the subject's m2m ``ROIs``
        folder plus ``thalamus_functional``.
    overwrite
        Replace existing masks when ``True``.  Existing masks are otherwise
        reused and reported with ``created=False``.
    """

    sid = _subject_id(subject_id)
    pm = get_path_manager(str(project_dir))
    m2m_dir = Path(pm.m2m(sid))
    t1_path = Path(pm.t1(sid))
    if not m2m_dir.is_dir():
        raise FileNotFoundError(f"Missing m2m folder for sub-{sid}: {m2m_dir}")
    if not t1_path.exists():
        raise FileNotFoundError(f"Missing SimNIBS T1 reference for sub-{sid}: {t1_path}")

    templates = find_thalamus_template_dir(project_dir, template_dir)
    _validate_templates(templates)

    roi_dir = Path(output_dir) if output_dir else Path(pm.rois(sid)) / ROI_SUBDIR
    roi_dir.mkdir(parents=True, exist_ok=True)

    results: list[ThalamusROIResult] = []

    for target in THALAMUS_TARGETS:
        side_masks: dict[str, tuple[np.ndarray, object, Path, dict]] = {}

        for side in THALAMUS_SIDES:
            source = _template_path(templates, target, side)
            output = _output_path(roi_dir, sid, target, side)
            metadata = _load_template_metadata(templates, target, side)
            created = overwrite or not output.exists()

            if created:
                _warp_volume(source, m2m_dir, output, t1_path)
                mask, img = _load_binary_mask(output)
                _save_binary_mask(mask, img, output)
                _write_sidecar(
                    output,
                    subject_id=sid,
                    target=target,
                    side=side,
                    voxel_count=int(mask.sum()),
                    source_metadata=metadata,
                    source_files=(source,),
                    m2m_dir=m2m_dir,
                )
            else:
                mask, img = _load_binary_mask(output)

            side_masks[side] = (mask, img, source, metadata)
            results.append(
                ThalamusROIResult(
                    subject_id=sid,
                    target=target,
                    side=side,
                    path=output,
                    voxel_count=int(mask.sum()),
                    created=created,
                )
            )

        bilateral_output = _output_path(roi_dir, sid, target, "bilateral")
        bilateral_created = overwrite or not bilateral_output.exists()
        left_mask, left_img, left_source, left_metadata = side_masks["left"]
        right_mask, _right_img, right_source, right_metadata = side_masks["right"]

        if bilateral_created:
            bilateral_mask = np.logical_or(left_mask, right_mask)
            _save_binary_mask(bilateral_mask, left_img, bilateral_output)
            bilateral_metadata = dict(left_metadata)
            bilateral_metadata["labels"] = (
                left_metadata.get("labels", []) + right_metadata.get("labels", [])
            )
            _write_sidecar(
                bilateral_output,
                subject_id=sid,
                target=target,
                side="bilateral",
                voxel_count=int(bilateral_mask.sum()),
                source_metadata=bilateral_metadata,
                source_files=(left_source, right_source),
                m2m_dir=m2m_dir,
            )
        else:
            bilateral_mask, _bilateral_img = _load_binary_mask(bilateral_output)

        results.append(
            ThalamusROIResult(
                subject_id=sid,
                target=target,
                side="bilateral",
                path=bilateral_output,
                voxel_count=int(bilateral_mask.sum()),
                created=bilateral_created,
            )
        )

    return results


def _discover_subjects(project_dir: Path) -> list[str]:
    simnibs_dir = project_dir / "derivatives" / "SimNIBS"
    subjects: list[str] = []
    for sub_dir in sorted(simnibs_dir.glob("sub-*")):
        sid = sub_dir.name.removeprefix("sub-")
        if (sub_dir / f"m2m_{sid}").is_dir():
            subjects.append(sid)
    return subjects


def main(argv: list[str] | None = None) -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project", required=True, help="BIDS project root")
    parser.add_argument(
        "--subjects",
        nargs="+",
        required=True,
        help="Subject IDs without sub- prefix, or 'all' for all m2m subjects",
    )
    parser.add_argument(
        "--template-dir",
        help="Optional directory containing thalamus_*_MNI.nii.gz templates",
    )
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Regenerate masks even if they already exist",
    )
    args = parser.parse_args(argv)

    project = Path(args.project)
    subjects = [_subject_id(s) for s in args.subjects]
    if subjects == ["all"]:
        subjects = _discover_subjects(project)
    if not subjects:
        raise SystemExit("No subjects found.")

    for sid in subjects:
        results = create_thalamus_functional_rois(
            project,
            sid,
            template_dir=args.template_dir,
            overwrite=args.overwrite,
        )
        print(f"sub-{sid}: wrote/verified {len(results)} functional thalamus ROIs")
        for result in results:
            status = "created" if result.created else "exists"
            print(
                f"  {result.target} {result.side}: "
                f"{result.voxel_count} voxels ({status}) -> {result.path}"
            )


if __name__ == "__main__":
    main()
